### ISSUE TITLE
forward plugin not compatible with roundcube 0.9 beta

### ISSUE THREAD

**Issue by sblaisot** [gianlucagiacometti/Roundcube-Forward#1]
Hi,

Due to changes in the way roundcube access database in the 0.9 beta version, the forward plugin doesn't work anymore starting with this version.

Error log says :
PHP Fatal error:  Class 'rcube_mdb2' not found in <PATH>/plugins/forward/lib/drivers/sql.php on line 39

this is related with the following changelog line of roundcube 0.9 :
- Another major change is the new database abstraction. In order to add support for SQLite3 the PEAR:MDB2 dependency was dropped and Roundcube now uses the native PHP Data Objects (PDO). ATTENTION: due a small lack in the MySQL PDO driver this version of Roundcube requires PHP 5.3 when using the MySQL database.

A workaround is to replace
$db = new rcube_mdb2($dsn, '', FALSE);
by
$db = rcube_db::factory($dsn, '', FALSE);

regards,

S.B.

**Comment by sblaisot** [comment]
for better compatibility with pre-è0.9 versions, it is in fact better to replace with 
                if (!class_exists('rcube_db')) {
                    $db = new rcube_mdb2($dsn, '', FALSE);
                } else {
                    $db = rcube_db::factory($dsn, '', FALSE);
                }

which can handle both situations.

regards,

S.B.

**Comment by gianlucagiacometti** [comment]
Thank you very much! as soon as I can I will update the official repository thanking you.

Spedito da Samsung Galaxy S2

-----Original Message-----

**Comment by IdahoPL** [comment]
When can we expect updated version? :)

**Comment by zuloo** [comment]
Hello, i guess i will fork it and offer you a pull request...

**Comment by gianlucagiacometti** [comment]
Great,
I printed my phd thesis today and I'll go for it within the end of the month.
Two minds work better!

Il 15 febbraio 2014 21:59:44 zuloo notifications@github.com ha scritto:

**Comment by IdahoPL** [comment]
Thank you, I'm eagerly waiting :)

**Comment by IdahoPL** [comment]
Hi,

Is this project alive?

**Comment by gianlucagiacometti** [comment]
I hope,
I'm starting working on a new version right now

**Comment by IdahoPL** [comment]
It's a great news :) If I may suggest one feature - it would be great to support postfixadmin's vacation alias format. postfixadmin use special alias format when vacation is active. It looks like this:

login#domain.tld@vacation.domain2.tld

I think forward should hide this type of alias from user, as it can be scary for regular user ;) If this type of alias is set then hide it and leave it alone, other plugin should manage vacation settings.

**Comment by gianlucagiacometti** [comment]
I'm back... at last! :-)
