### ISSUE TITLE
Plugin conflicts with Password plugin

### ISSUE THREAD

**Issue by iBL1nK** [gianlucagiacometti/Roundcube-Forward#7]
When used with this plugin: https://github.com/roundcube/roundcubemail/tree/master/plugins/password
The "Foward" tab button in setting replaced the "Password" button. Therefore the user is unable to access the password plugin.

**Comment by spacepolitix** [comment]
Solved by replacing 

```
$rcmail_config['plugins'] = array('password'); 
...
$rcmail_config['plugins'] = array('forward');
```

with

`$rcmail_config['plugins'] = array('password','forward');`
